title: kd.io by Koding
email: support@koding.com
repository: koding/kdio
description: >
  Instantly share, scale and manage development environments in cloud.
keywords: >
  development environment, cli tool, dev environment,
  cloud development environment, virtual dev environment,
  test environment, docker, aws, vagrant, azure, rackspace
baseurl: ""
url: "https://koding.github.io/kdio"
permalink: /blog/:year/:month/:title/
paginate_path: "/blog/page/:num"
paginate: 5
timezone: America/Los_Angeles
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
gems:
- jekyll-redirect-from
sass:
  style: compressed
  sass_dir: _css
social:
  twitter: https://twitter.com/koding
  github:  https://github.com/koding
  facebook:  https://facebook.com/koding
  linkedin:  https://linkedin.com/company/koding

